language: java
jdk: oraclejdk8
sudo: required
dist: trusty

env:
  global:
    secure: "Lvg5wIyBz1w85QBUJzeFxcQ1hmt/l5GIRw8dgANdiWsoWcayLu7FBQCnEfmN3g6Tr0rIDaiGr2SST6xJxhCFnD1TQ9Vl/1DoLvWy2uNcpaGzgAqVO9paBrGcpjx+urs9jS5IMI8idGJpOeQfr2zQ+4Q5eRI7wrPc7X9g/HDHwafNz8NYiuVTBEwlksywQxLzWCBiISwSw8dpuGdc2DCkCx+qSdycVt9RCRTSYx9ge2i5HHP0exgmsgP00Z/2iOqHHx+KjbdyajOezGf+zyGo8fHDkwKMIgSKf4NLZHZQxLAdCXQQhC7m1+KkD4bVF4iHFIWZn5WxpxBayLIcQg+Jffw8spY1+loEYo66BsMpUsN4M+aFk2Jkj+JktmC+nZsl/MNfSrpbfRelx/dlH2pki+bt1jpIypQxfs/oYxhTM+IA619aGVHypmvX1sr8B2WkRfk+6t2iv/wZ8hn3jII2Zzy/vtXThiEVix7y8EBVRF5CXkr97APEuuagVQjhFcjWdjYPmdiZC63T5weUpSR6h/OeJYza+Y6U0t4QmfDb2sZVT2vbVLfVLo3SX3bFFe+V+5T6ZzqV/bQuRxpzLsPu0HuLW80hwJcmowZG4Q4sDfS1vNhe/puKDgQP6t5YYr1Xz544sfFBTo+W0igiVQdGO3ovRnae18wl4zepyhZX7bc="

before_install:
- sudo dpkg --add-architecture i386
- sudo add-apt-repository -y ppa:arx/release
- sudo add-apt-repository -y ppa:ubuntu-wine/ppa
- sudo apt-get update
- sudo apt-get install -y -q innoextract wine python-software-properties
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- wine --version
- innoextract --version
- export APP_VERSION=`sed '/^\#/d' build.properties | grep '^app.version' | tail -n 1 | cut -d "=" -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'`
- echo $APP_VERSION

script:
- ant do.setup

before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=v$APP_VERSION.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for $GIT_TAG"
- git push -q https://${GH_TOKEN}@github.com/crazy-max/crossfit-reader --tags
- ls -R

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "Lvg5wIyBz1w85QBUJzeFxcQ1hmt/l5GIRw8dgANdiWsoWcayLu7FBQCnEfmN3g6Tr0rIDaiGr2SST6xJxhCFnD1TQ9Vl/1DoLvWy2uNcpaGzgAqVO9paBrGcpjx+urs9jS5IMI8idGJpOeQfr2zQ+4Q5eRI7wrPc7X9g/HDHwafNz8NYiuVTBEwlksywQxLzWCBiISwSw8dpuGdc2DCkCx+qSdycVt9RCRTSYx9ge2i5HHP0exgmsgP00Z/2iOqHHx+KjbdyajOezGf+zyGo8fHDkwKMIgSKf4NLZHZQxLAdCXQQhC7m1+KkD4bVF4iHFIWZn5WxpxBayLIcQg+Jffw8spY1+loEYo66BsMpUsN4M+aFk2Jkj+JktmC+nZsl/MNfSrpbfRelx/dlH2pki+bt1jpIypQxfs/oYxhTM+IA619aGVHypmvX1sr8B2WkRfk+6t2iv/wZ8hn3jII2Zzy/vtXThiEVix7y8EBVRF5CXkr97APEuuagVQjhFcjWdjYPmdiZC63T5weUpSR6h/OeJYza+Y6U0t4QmfDb2sZVT2vbVLfVLo3SX3bFFe+V+5T6ZzqV/bQuRxpzLsPu0HuLW80hwJcmowZG4Q4sDfS1vNhe/puKDgQP6t5YYr1Xz544sfFBTo+W0igiVQdGO3ovRnae18wl4zepyhZX7bc="
  file:
    - ${HOME}/build/crazy-max/crossfit-reader/bin/setup/crossfit-reader-setup.exe
  on:
    repo: crazy-max/crossfit-reader
    tags: false

branches:
  except:
    - /^v[0-9]/
