language: java
jdk: oraclejdk8
sudo: required
dist: trusty

env:
  global:
    secure: Dqiw1Dxjzx8th7XEZDofrkqNOVVizt96wfzjKC5MkX5fJmBwXtIFoRyxPeOPRKB3GCKmO2rzQSuLS1vzQfcWbxpzsKwQpPQcc68FlR1wukzc+CnNHw7BkSRCqUCR4BdB8UkDczyxvVGleE2WK/KjuOAyaRsJQmmWJ5thgzJD54rzqohL9XWpLY2jcIhFSQ6XgkBcJ5KYnFQgfkaIvtTvr4qdb4HB3H6AazExuYV+Azj8w54A4gbAPHEvZFm7NiZ0EAU/g8oguLcvOXC8RFkAf37z7RVVJC8DjhoYC2j/JyuViZ8OLp4QTgi3qEciQpTY8IxEHN7yoCWWuziARCGFOytMhE7H3yganRNWLr1wn3idK7C3y2n/l19/GZ1i5gbUhLMGXvZ4JVFSmLXKT0y3VLqMLjv69p98aY13oYgOt/VsU0lt90BAT07nEqNcJ8H+TQ3sW8qX4vMm8BYLLrdsFfWp3aB5ZIAPf2yNwTyjInASo8TG9JpBQqe03nIWjZZQmJ0KW22ZBzIuZm5aiUrEWtH0NPLTwIAvQWEIr3Vc2MC/HNwcTjnYpgkoViFkB1+pITVIrXgVbEC/Bk//2Lkc3txhyoYe2WpfIgAC++QhMz2wfI3tkJL+oDJ5ElP6KqG7LXGypFNxjzEnRGDUsuPOpkfwuKL3DU8LwJ8LDvPwFH0=

before_install:
- sudo dpkg --add-architecture i386
- sudo add-apt-repository -y ppa:arx/release
- sudo add-apt-repository -y ppa:ubuntu-wine/ppa
- sudo apt-get update
- sudo apt-get install -y -q innoextract wine python-software-properties
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- WINEARCH=win32 WINEPREFIX=~/.wine winecfg
- wine --version
- innoextract --version
- export APP_VERSION=`sed '/^\#/d' build.properties | grep '^app.version' | tail -n 1 | cut -d "=" -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'`
- echo $APP_VERSION

script:
- ant do.setup

after_success:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=v$APP_VERSION.$TRAVIS_BUILD_NUMBER
- git commit -m "Publish release $GIT_TAG"
- git tag $GIT_TAG -a -m "Generated tag from Travis CI"
- git push --quiet https://${GH_TOKEN}:github.com/crazy-max/crossfit-reader $GIT_TAG > /dev/null 2>&1

#deploy:
#  provider: releases
#  file: ${HOME}/build/crazy-max/crossfit-reader/bin/setup/crossfit-reader-setup.exe
#  skip_cleanup: true
#  on:
#    repo: crazy-max/crossfit-reader
