sudo: required
language: java
jdk: oraclejdk7
addons:
  apt:
    packages:
    - wine
before_install:
  - sudo add-apt-repository -y ppa:arx/release
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y -q innoextract wine python-software-properties ia32-libs lib32ncurses5 lib32z1
  - wine --version
  - innoextract --version
script:
  - ant do.setup
