language: java
jdk: oraclejdk8
sudo: required
dist: trusty

env:
  - secure: "DAxsjIwXM9x+IpsWxfeIqP+yJkrt4qvUgCZ7jG6GvEaTH7w7JowHq8aDngy1TeZ3NmptGw/YuUEXRNCDzYBsiwtxeGQXiQaeJYcmAmIA7Aqx+TbEFjTJRJzPTZ3GJHBToD8qx+gDj++2RS52AxfFhe5gcmYuLi5lraPdD7jsBw35vZlU9VO1JbFc0WapGCn3wcaeFarxVddTdsZyXTWaOntziwGgkcIa9cwbtUEMPD4QS7Y+36naswJ2sEaBDetBd83AtVZ1Buwxm3aJM/slyjY6s/OuFCLVCwEG+roCocTQoVyeCiWykA4hd0fFWa4Y1CZxSZVt1IrVi+58VucGYYNYxFkB6rQjD5U/MCLYHhyCXSiUe/GNWKUahSPgy+diB3v949biZnLuaDUsKNRXG73IfZtOygNnR+JueQITopS5VoKjXmWvZBSeDY1OqNI/54aoa4GwyzRUNj3Dq56JAjub18JgX8oK0eizofu6wqIWYbIAx5x7Q3WuhMU8cukL6kA/EkNLzwRESyEBBCXsv8huiRuY17Njs+Kz3w6cHW3END1glk+X+L1/NNZR2kF58xiz39AHbr+6kgLBpxUgqVhoHozqEsjQgaYO74H+HCTZpEentwuoZjOkBVBHyiypj33ImT8xURhUF9QxA4WVlpgTqPvr4KctWM2W8tZyyIA="

before_install:
  - sudo dpkg --add-architecture i386
  - sudo add-apt-repository -y ppa:arx/release
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo apt-get update
  - sudo apt-get install -y -q innoextract wine python-software-properties
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - wine --version
  - innoextract --version
  - sh src-build/travisSwitchJdk.sh
  - source ~/.bash_profile
  - export APP_VERSION=`sed '/^\#/d' build.properties | grep '^app.version' | tail -n 1 | cut -d "=" -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'`
  - echo $APP_VERSION

script:
  - gradle antClean getDeps antRelease

after_success:
  - export PREVIOUS_VERSION=`git describe --abbrev=0 --tags | cut -c 2-`
  - echo $PREVIOUS_VERSION
  - sh src-build/travisTag.sh
  - source ~/.bash_profile

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    - secure: Z1x+9GA+l9u/QNus2rWaVCfwDII/oqK4UDRJCsLyhHkP/G4UJXED6J5ZlDduxrmvIvGk9GfAeVrxZzXDdP7nrDn1rKln7zlKy8vLEYL9j43H6D0cMZKHodlq48g+5RTBDsEY0RCMzzZrCL3nEfu68I/YZ5nPE0vqPiPmDCnjdlGVZSDaMpsoCxfVxrbQE8RIKeL/bHdJcrAvh+ZTQLxu1QakcLjrJnh/e47mE1e4pakL3/NmlQc0EEayolRstajz/2IbGGDT3IFofrP6qMWRwMAewV1+3OZHF1kaCEmtvD4fa155aS/iadQS6AQl41LQKa+xKJ/ZN9Ee6ahrJVzdjTxQ2M7kXGMdEAJltDdWvEwi5gD7rYXLRfAiKanu0ctcsGIdyd4lxMAwgurPqY/L7F0mw0YNRtGQn7OdjnmtC2yBS3aMh+CiaGTHq75XWbq8XIzHNtWFm/GPh44ZKeX0w1h6cgNyViT7skvZDJDbp3WFHWVx8X0oXry+lZZv8hYvUDJYS/NFteAsxlS+e6uOg7RaOpl4dWa7B/zS+a82CLBGPdhcHREYAbX0EhXf9pzjmZLX/TpvQ4+zzi8S705/OZXN0bxxDHye+wNi6FNhXRfClpfWdniHX85OeJOKllYkXVx2sevN69VDhdsb6wOccJo40nDmh2/VmbbTbcFB3bg=
  file:
    - build/ant/setup/crossfit-reader-setup.exe
  on:
    condition: $DO_DEPLOY = 1
    repo: crazy-max/crossfit-reader
    tags: false

branches:
  except:
    - /^v[0-9]/
