language: java
jdk: oraclejdk8
sudo: required
dist: trusty

before_install:
- sudo dpkg --add-architecture i386
- sudo add-apt-repository -y ppa:arx/release
- sudo add-apt-repository -y ppa:ubuntu-wine/ppa
- sudo apt-get update
- sudo apt-get install -y -q innoextract wine python-software-properties
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- wine --version
- innoextract --version
- export PREVIOUS_VERSION=`git describe --abbrev=0 --tags | cut -c 2-`
- echo $PREVIOUS_VERSION
- export APP_VERSION=`sed '/^\#/d' build.properties | grep '^app.version' | tail -n 1 | cut -d "=" -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'`
- echo $APP_VERSION
- chmod +x gradlew

script:
- gradle antClean getDeps antRelease

before_deploy:
- chmod +x src-build/travisTags.sh
- sh src-build/travisTags.sh
- source ~/.bash_profile

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: HK49CZDJGtB9wTjyah60XRNNKUEmvJcAhq0fsPZrsRUptj0fixNfjJWTTGSno3rER6l+2dBcuSm3hFBsog3dDUcAd5Jm5rGIR4SsZ66H+PXePJXynMZ9p1k9Yeox3iSuGy/mTkj0TkT7QV2GhEXYQkfPrK+iPTsmnlmjIehTCrIxse02wUrRqnbr36YkIBZZm9fSdPjcPRUqvnVta0q/meDQOqICH5oaKqoXiS4OlARFjpi3j7toxjnMPTfIsACR2HUgNeZ2kiPhOkco60+cze3yW99NHq0XogP3S2iT9HJBsM6CQSJVoKplkx6kmMqk4Emdsv7k79lAKkUqTq0AltnzFqYGe+16oo0q3LBjuXM8Gkjz4YqAbnKgOa5Lx+sYdGS5w2Vz/ycA+rfiefBOMf/VxdaF4QxMZ0g56quDO8Akrx3n1p9QU710Hk4CazyaK733I7mZ6k6Rgp1hQrpHJSqGzJMnJ+mnOAdCNy42WbNDQzXbSHbZApERWA1mQsBd/XT/uUXCYa9Tb8mSAfHYyvYDsAanF1U2QyoO5gZ3HCUt1bFMrJudtRkBj2gcFretu2io3qseJ/Fp6I7MJz4qp/6Edgs9+p8KGQhZKDA+n8I23BexUOZOnKNpNUau4EwF2NJQ5IWDEdWQoAdWk3BqKreC0fnTqWxvf7qyzOF4JdM=
  file:
    - ${HOME}/build/crazy-max/crossfit-reader/bin/setup/crossfit-reader-setup.exe
  on:
    condition: $DO_DEPLOY = 1
    repo: crazy-max/crossfit-reader
    tags: false

branches:
  except:
    - /^v[0-9]/
