version: '{build}'

clone_folder: C:\projects\crossfit-reader

environment:
  JAVA_HOME: C:\jdk

install:
  - ps: |
      choco install jdk8 --version 8.0.152 -params 'installdir=C:\\jdk'
      choco install ant
      refreshenv
      $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
  - java -version
  - gradlew.bat --version
  - ant -version

configuration:
  - Release

build_script:
  - gradlew.bat antClean getDeps antRelease -u -d -S

after_build:
  - ps: |
      $env:APP_VERSION = Get-Content C:\projects\crossfit-reader\build\ant\version.dat -Raw
      Write-Host "App version: $env:APP_VERSION"

artifacts:
  - path: 'build\ant\setup\*'
    name: release

deploy:
  tag: v$(APP_VERSION)
  release: v$(APP_VERSION)
  description: 'New release: $(APP_VERSION)'
  provider: GitHub
  auth_token:
    secure: BGz5Z+cKh7a/UOFxIfBfZYho8Ghf3bO3LvaX70mdgiG1UDJhtW3FUGDjBrwyZglf
  artifact: release
  draft: true
  prerelease: false
  on:
    branch: master

notifications:
  - provider: Webhook
    url:
      secure: Vf+59lgCDVyte9kmHKwYXPR7uc6THo9IH6mQwiPAWOCQHUoLCQrGFupj30nk4MUggyWss3ydobo/z1sQ6iYabwAkkwI6H9XNmjgGgTVlCJoBISHN6yTwxLgkYMi40qT4Mevr9XVgd6EmJqOi257YjQ==
    method: post
