#!/bin/sh
unset DISPLAY

outputpath=$1
setupname=$2
scriptname=$3
echo "ISCC OutputPath: $outputpath"
echo "ISCC SetupName: $setupname"
echo "ISCC ScriptName: $scriptname"

chown -R `who am i | awk '{print $1}'`. ~/".wine"

[ -f "$scriptname" ] && scriptname=$(winepath -w "$scriptname")
wine "C:\innosetup\app\ISCC.exe" /O"$outputpath" /F"$setupname" "$scriptname"
