#!/bin/sh
echo "Start wineJdk..."

winePath=$1
jdkUrl=$2
echo "* WinePath: $winePath"
echo "* JdkUrl: $jdkUrl"

wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" "$jdkUrl" -O "$winePath/jdk.exe"
DISPLAY=:99.0 wine start /wait "C:\jdk.exe" /s INSTALLDIR=C:\jdk
