#!/bin/sh
unset DISPLAY

winePath=$1
jdkUrl=$2
echo "WinePath: $winePath"
echo "JdkUrl: $jdkUrl"

wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" "$jdkUrl" -O "$winePath/jdk.exe"
wine "C:\jdk.exe" /s INSTALLDIR=C:\jdk
